default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: password
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: jewelry_app_development

# production:
#   adapter: mysql2
#   encoding: utf8mb4
#   pool: 5
#   database: Jwellery_Backend_production
#   username: uditk660
#   password: J#SunnyBunny48XDev!
#   socket: /var/run/mysqld/mysqld.sock
#   collation: utf8mb4_unicode_ci