default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: jwe
  password: password
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: jewelry_app_development

production:
  <<: *default
  database: Jwellery_Backend_production
  username: uditk660
  password: J#SunnyBunny48XDev!