development:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] || "6f4a9b2d8c1e7f3a5d9b0c6e4f8a1b2c3d4e5f60718293a4b5c6d7e8f9012345" %>

test:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] || "1a2b3c4d5e6f7081920a3b4c5d6e7f8091a2b3c4d5e6f7081920a3b4c5d6e7f8" %>

production:
  # In production, set SECRET_KEY_BASE in the environment.
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] || "a7dbf434d0acb8d60985c1535779f2280a46bdbd370d14ae7ccaeac043296e59bd07d71353e105cab3c756197e6c40f4db1bce3c98bded01ca6257b247fe5a0c" %>